language: perl

install:
  - sudo apt-get update
  - sudo apt-get install libedit-dev
  - cpanm -n -v https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Editline-0.02.tar.gz
  - cpanm -n -v --installdeps .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - perl Makefile.PL
  - make
  - make test
  - make install

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
